SHELL:=/bin/bash -o pipefail

ALPINE_MAJOR=3.6
ALPINE_VERSION=3.6.1
ALPINE_ARCH=x86_64

ALPINE_TAR=alpine-minirootfs.tar.gz
JRE_TAR_REMOTE=sgxlkl_openjdk_jre_alpine_8.121.13-r0.tar.gz
JRE_TAR=jre8-no-segv-nommap.tar.gz

ROOT_FS=sgxlkl-java-fs.img
MOUNTPOINT=/media/ext4disk
#IMAGE_SIZE_MB=400
IMAGE_SIZE_MB=1600

ESCALATE_CMD=sudo

#STORM_RELEASE_TAR=apache-storm-1.2.2.tar.gz
STORM_RELEASE_TAR=apache-storm-2.0.0.tar.gz
#STORM_HOME_DIR=apache-storm-1.2.2
STORM_HOME_DIR=apache-storm-2.0.0
STORM_LIB_DIR=${STORM_HOME_DIR}/lib
STORM_EG_DIR=${STORM_HOME_DIR}/examples/storm-starter/src/jvm/org/apache/storm/starter
STORM_EG_SRC=ExclamationTopology.java
STORM_EG_CLASS=org.apache.storm.starter.ExclamationTopology
#STORM_EG_SRC=WordCountTopology.java
#STORM_EG_CLASS=org.apache.storm.starter.WordCountTopology
#STORM_STARTER_JAR=storm-starter-1.2.2.jar
STORM_STARTER_JAR=storm-starter-2.0.0.jar
RUN_COMMENT=rm_fork
LOGPATH=${CURDIR}/log
LOGFILE=${LOGPATH}/${shell date +'%Y.%m.%d-%H:%M:%S'}${suffix ${STORM_EG_CLASS}}_${RUN_COMMENT}.log
#TEE2LOG=
TEE2LOG= 2>&1 | tee ${LOGFILE}

STORM_DEPS= \
	clojure-1.7.0.jar \
	log4j-api-2.8.2.jar \
	log4j-slf4j-impl-2.8.2.jar \
	objenesis-2.1.jar \
	storm-core-1.2.2.jar \
	disruptor-3.3.2.jar \
	log4j-core-2.8.2.jar \
	metrics-core-3.1.0.jar \
	servlet-api-2.5.jar \
	kryo-3.0.3.jar \
	log4j-over-slf4j-1.6.6.jar \
	minlog-1.3.0.jar \
	slf4j-api-1.7.21.jar \

LD_LIBRARY_PATH=/opt/j2re-image/lib/amd64:/opt/j2re-image/lib/amd64/jli:/opt/j2re-image/lib/amd64/server 

SGXLKL_PARAMS=\
  SGXLKL_TAP=sgxlkl_tap0 \
  SGXLKL_HD=${PWD}/${SGXLKL_ROOTFS} \
  SGXLKL_VERSION=1 \
  SGXLKL_ESLEEP=100 \
  SGXLKL_SSLEEP=400 \
  SGXLKL_ESPINS=500 \
  SGXLKL_SSPINS=500 \
  SGXLKL_STHREADS=16 \
  SGXLKL_ETHREADS=8 \
  SGXLKL_TRACE_SYSCALL=0 \
  SGXLKL_VERBOSE=1 \
  SGXLKL_TRACE_MMAP=0 \
  SGXLKL_STACK_SIZE=3097152 \
  SGXLKL_HEAP=2048M \
  SGXLKL_KEY=../../../build/config/enclave_debug.key \
  SGXLKL_HOSTNAME=localhost \
  SGXLKL_TRACE_THREAD=0 \
  SGXLKL_NON_PIE=0

# SGXLKL_TRACE_THREAD=1 \
# SGXLKL_STACK_SIZE=3097152 \
# SGXLKL_HEAP=1919715200 \
# SGXLKL_ESLEEP=1 \
# SGXLKL_SSLEEP=4000 \
# SGXLKL_ESPINS=50000 \
# SGXLKL_SSPINS=500 \
# SGXLKL_HEAP=1060270000 \
# SGXLKL_HEAP=1919715200 \

JVM_PARAMS=\
  -XX:+UseMembar \
  -XX:InitialCodeCacheSize=8000k \
  -XX:ReservedCodeCacheSize=12000K \
  -Xms256m \
  -Xmx256m \
  -XX:CompressedClassSpaceSize=12000K \
  -XX:+UseCompressedClassPointers \
  -XX:+AssumeMP \
  -XX:+PreserveFramePointer \
  -Xdebug

#  -XX:+PrintCompilation
#  -XX:OnError="gdb - %p" \

JAVA_PARAMS=\
  -client 

#  -Djava.io.tmpdir=/app/tmp
# verbose 

APP_PARAMS=\
  -Ddaemon.name= \
  -Dstorm.options= \
  -Dstorm.home=/app \
  -Dstorm.log.dir=/app/logs \
  -Dstorm.conf.file=/app/conf.yaml \
  -Dstorm.jar=/app/${STORM_STARTER_JAR} \
  -Dstorm.dependency.jars= \
  -Dstorm.dependency.artifacts={} \
  -Dlogging.sensitivity=DEBUG \
  -Djava.net.preferIPv4Stack=true \
  -cp /app/:/app/lib/*:. 

#  -Dsupervisor.blobstore.download.thread.count=5 \
#  -Dsupervisor.worker.shutdown.sleep.secs=30 \

.DELETE_ON_ERROR:
.PHONY: all clean

all: ${ROOT_FS}

clean:
	test -f HelloWorld.class && rm HelloWorld.class || true
	test -f ${ROOT_FS} && rm ${ROOT_FS} || true
	test -d ${CURDIR}/app && rm -rf ${CURDIR}/app || true

${ALPINE_TAR}:
	curl -L -o "$@" "https://nl.alpinelinux.org/alpine/v${ALPINE_MAJOR}/releases/${ALPINE_ARCH}/alpine-minirootfs-${ALPINE_VERSION}-${ALPINE_ARCH}.tar.gz"

${STORM_RELEASE_TAR}:
	curl -L -o "$@" "http://mirror.vorboss.net/apache/storm/apache-storm-1.2.2/apache-storm-1.2.2.tar.gz"

storm-deps: ${STORM_RELEASE_TAR}
	tar -C ${CURDIR} -xf ${STORM_RELEASE_TAR}
	[ -d ${CURDIR}/app/lib ] ||mkdir -p ${CURDIR}/app/lib
	cp  ${CURDIR}/${STORM_LIB_DIR}/*.jar ${CURDIR}/app/lib
#	cp  ${CURDIR}/*.yaml ${CURDIR}/app/
#	cp ${CURDIR}/storm-starter-1.2.2.jar ${CURDIR}/app/lib
        
#ExclamationTopology.class: storm-deps
#	javac -classpath ${CURDIR}/${STORM_LIB_DIR}/*:. -d ${CURDIR}/app ${CURDIR}/${STORM_HOME_DIR}/examples/storm-starter/src/jvm/org/apache/storm/starter/ExclamationTopology.java

Example.class: storm-deps
	echo "Compiling ${CURDIR}/${STORM_EG_DIR}/${STORM_EG_SRC}"
	javac -classpath ${CURDIR}/${STORM_LIB_DIR}/*:${CURDIR}/${STORM_STARTER_JAR}:. -d ${CURDIR}/app ${CURDIR}/${STORM_EG_DIR}/${STORM_EG_SRC} 

${ROOT_FS}: ${ALPINE_TAR} buildenv.sh Example.class
	dd if=/dev/zero of="$@" count=${IMAGE_SIZE_MB} bs=1M
	mkfs.ext4 "$@"
	${ESCALATE_CMD} /bin/bash -euxo pipefail -c '\
                mkdir -p ${MOUNTPOINT}; \
                mount -t ext4 -o loop "$@" ${MOUNTPOINT}; \
                tar -C ${MOUNTPOINT} -xvf ${ALPINE_TAR}; \
                cp /etc/resolv.conf ${MOUNTPOINT}/etc/resolv.conf; \
                install buildenv.sh ${MOUNTPOINT}/usr/sbin; \
                mkdir -p ${MOUNTPOINT}/app/lib; \
                mkdir -p ${MOUNTPOINT}/app/tmp; \
                cp -pvR ${CURDIR}/app/* ${MOUNTPOINT}/app; \
		mkdir -p ${MOUNTPOINT}/opt; \
                [ -f ../${JRE_TAR} ] || curl -L -o ../${JRE_TAR} "https://lsds.doc.ic.ac.uk/files/${JRE_TAR_REMOTE}"; \
                tar -xf ../${JRE_TAR} -C ${MOUNTPOINT}/opt; \
		curl -L -o "${MOUNTPOINT}/opt/j2re-image/lib/amd64/server/libjvm.so-gdb.py" "https://icedtea.classpath.org/people/adinn/unwinder/file/f50e52519fb9/dbg8.py"; \
		chroot ${MOUNTPOINT} /bin/sh /usr/sbin/buildenv.sh; \
                umount ${MOUNTPOINT}; \
                chown ${USER} "$@"; \
'

test: ${ROOT_FS}
	echo "Running storm enclave example:"
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH} ${SGXLKL_PARAMS} ${CURDIR}/../../../build/sgx-lkl-run ${CURDIR}/${ROOT_FS}  /opt/j2re-image/bin/java ${JVM_PARAMS} ${JAVA_PARAMS} ${APP_PARAMS} ${STORM_EG_CLASS} ${TEE2LOG}

test_gdb: ${ROOT_FS}
	echo "Running storm Hello World example under gdb:"
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH} ${SGX_PARAMS} ../../../gdb/sgx-lkl-gdb --args ${CURDIR}/../../../build/sgx-lkl-run ${CURDIR}/${ROOT_FS}  /opt/j2re-image/bin/java ${JVM_PARAMS} ${JAVA_PARAMS} ${APP_PARAMS} org.apache.storm.starter.ExclamationTopology

